<template>
  <div class="index container">
    <div class="card" v-for="playlist in playlists" :key="playlist.id">
      <div class="card-content">
        <router-link :to="{ name: 'EditPlaylist', params: {playlist_slug: playlist.slug} }">
          <i class="material-icons edit">edit</i>
        </router-link>
        <i class="material-icons delete" @click="deletePlaylist(playlist.id)">delete</i>
        <h2 class="indigo-text">{{ playlist.title }}</h2>
        <ul class="attributes">
          <!-- id is generated by firestore -->
          <li v-for="(attribute, index) in playlist.attributes" :key="index">
            <span class="chip">{{ attribute }}</span>
          </li>
        </ul>
        <p class="center-align">
          <a class="waves-effect waves-light btn-large blue">Play</a>
        </p>
      </div>
    </div>
  </div>
</template>

<script>
// note: firestore is the database
import database from '@/firebase/init'
export default {
  name: 'Index',
  data () {
    return {
      playlists: [ ]
    }
  },
  methods: {
    deletePlaylist(id){
      // delete doc from firestoreApp
      database.collection('playlists').doc(id).delete().then(() => {
        // update frontend
        this.playlists = this.playlists.filter(playlist => {
          return playlist.id != id
        })
      })

    }
  },
  created(){
    // fetch info from firestore
    database.collection('playlists').get().then(snapshot => {
      snapshot.forEach(doc =>{
        // console.log(doc)
        // console.log(doc.data())
        // console.log(doc.id)
        let playlist = doc.data()
        playlist.id = doc.id
        this.playlists.push(playlist)
      })
    })
  }
}
</script>

<!-- Add "scoped" attribute to limit CSS to this component only -->
<style>
  .index{
    display: grid;
    grid-template-columns: 1fr 1fr 1fr;
    grid-gap: 30px;
    margin-top: 60px;
  }
  .index h2{
    font-size: 1.8em;
    text-align: center;
    margin-top: 0px;
  }
  .index .attributes{
    margin: 30px auto;
  }
  .index .attributes li {
    display: inline-block;
  }
  .index .delete {
    position: absolute;
    top: 4px;
    right: 4px;
    cursor: pointer;
    color: #aaa;
    font-size: 1.4em;
  }
  .index .edit {
    position: absolute;
    cursor: pointer;
    color: #aaa;
    top: 4px;
    left: 4px;

  }
</style>
