<template>
  <div class="index">
    <div class="title container">
      <div class="input-field">
        <input type="text" name="filter" v-on:keyup="filterCollection" v-model="filter" class="filter-input">
        <label for="filter">Filter</label>
      </div>

      <a href="#" class="waves-effect waves-light btn">
        <router-link :to="{ name: 'AddPlaylist'}">
          <i class="material-icons valign-wrapper">add</i><span>Create New Playlist</span>
        </router-link>
      </a>

    </div>


    <div class="index-viewport container row">
      <div class="card invisible col l3 m4 s12" v-for="playlist in displayPlaylists" :key="playlist.id">
        <!-- filter -->
        <!-- <div v-if="(filter && find(playlist.attributes)) || !filter"> -->


          <div class="card" >
            <div class="card-image">
              <a v-bind:href="'https://www.youtube.com/results?search_query='+ playlist.attributes">
                <img src="@/assets/placeholder.jpg">
              </a>
            </div>


            <div class="card-content">
              <router-link :to="{ name: 'EditPlaylist', params: {playlist_slug: playlist.slug} }">
                <i class="material-icons edit">edit</i>
              </router-link>
              <i id="delete" class="material-icons delete" @click="deletePlaylist(playlist.id)">delete</i>

              <!-- <ul class="attributes"> -->
                <!-- id is generated by firestore -->
                <!-- <li v-for="(attribute, index) in playlist.attributes" :key="index"> -->
                  <!-- <span class="chip">{{ attribute }}</span> -->
                <!-- </li> -->
              <!-- </ul> -->
              <p class="center-align">
                <a v-bind:href="'https://www.youtube.com/results?search_query='+ playlist.attributes">
                  <i class="material-icons play">
                    play_arrow
                  </i>
                </a>
              </p>
            </div>
          </div>
          <div class="info">
            <h2 class="indigo-text">{{ playlist.title }}</h2>
            <p v-if="playlist.user" class="center-align author">Created by: <span>{{ playlist.user }}</span></p>
            <p v-if="!playlist.user" class="center-align author"><span>Unknown</span></p>
          </div>
        <!-- </div> -->
      </div>

      <div class="center empty-playlist-feedback" v-if="!displayPlaylists">
        <h2>Sorry, Nothing is Here</h2>
      </div>


    </div>

  </div>
</template>

<script>
// note: firestore is the database
import firebase from 'firebase'
import database from '@/firebase/init'

export default {
  name: 'Index',
  data () {
    return {
      user: null,
      filter: null,
      lastFilter: null,
      playlists: [ ],
      displayPlaylists: []
    }
  },
  methods: {
    deletePlaylist(id){
      // delete doc from firestoreApp
      database.collection('playlists').doc(id).delete().then(() => {
        // update frontend
        this.playlists = this.playlists.filter(playlist => {
          return playlist.id != id

        })
        // TODO: asynchronous. Might be problemnatic
        this.displayPlaylists = this.playlists
      })

    },
    filterAttributes(attributes){
      for (const attr of attributes) {
        let filtered = attr.substring(0, this.filter.length).toLowerCase();
        let filter = this.filter.toLowerCase();
        if(filter === filtered){
          return true;
        }
      }
    },
    filterTitle(title){
      let filtered = title.substring(0, this.filter.length).toLowerCase();
      if(this.filter.toLowerCase() == filtered){
        return true;
      }
    },
    filterCollection(){
      // reset playlist with backspace
      if(this.lastFilter && this.filter){
        if(this.lastFilter.length > this.filter.length){
          this.displayPlaylists = this.playlists;
        }
      }
      this.lastFilter = this.filter


      let notFound = true;
      if(this.filter && this.displayPlaylists){
        this.displayPlaylists = this.displayPlaylists.filter( playlist => {
          // filter by title
          let found = this.filterTitle(playlist.title);

          if (!found){
            found = this.filterAttributes(playlist.attributes);
          }


          return found;
        })
        if(this.displayPlaylists.length == 0) {
          this.displayPlaylists = null;
        }
      }
      else if(!this.filter || this.displayPlaylists){
        this.displayPlaylists = this.playlists
      }
    }
  },



  created(){
      firebase.auth().onAuthStateChanged((user) => {
        if(user){
          this.user = user
        } else {
          this.user = null
        }
      })
    // fetch info from firestore
    database.collection('playlists').get().then(snapshot => {
      snapshot.forEach(doc =>{
        let playlist = doc.data()
        playlist.id = doc.id
        this.playlists.push(playlist)
        this.displayPlaylists = this.playlists
      })
    })
  }
}
</script>

<!-- Add "scoped" attribute to limit CSS to this component only -->
<style>

#delete:hover {
  color: red;
}

  .card .info{
    padding-top: 10px;
  }

  .card .info .author{
    margin-top: -10px;
  }


  .card-content{
    background-color: #E5E5E5;
  }

  .card-content p span{
    font-weight: bold;
  }

  .index .title {
    width: 300px;
    margin-top: 30px;
    display: grid;
  }

  .index .title .btn{
    border-radius: 20px;
    background-color: #495069;
  }

  .index .title a{
    color: white;
  }

  .index .title span{
    position: absolute;
    top: 0;
    left:0;
    right: 0;
    height: auto;
  }

  .index .invisible {
    box-shadow: none;
  }

  .index .material-icons{
    font-size: 2em;
  }

  /* .index-viewport{
    display: grid;
    grid-template-columns: 1fr 1fr 1fr;
    grid-gap: 30px;
    margin-top: 60px;
  } */

  .index-viewport{
    margin-top: 10px;
  }

  .index-viewport h2{
    font-size: 1.8em;
    text-align: center;
    margin-top: 0px;
  }
  .index-viewport .attributes{
    margin: 30px auto;
  }
  .index-viewport .attributes li {
    display: inline-block;
  }
  .index-viewport .delete {
    position: absolute;
    left: 4px;
    cursor: pointer;
    color: #aaa;
  }
  .index-viewport .edit {
    position: absolute;
    cursor: pointer;
    color: #aaa;
    right: 4px;
  }
  .index-viewport .empty-playlist-feedback{
    margin-top: 100px;
  }

</style>
